apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: memo-server
  annotations:
    nginx.ingress.kubernetes.io/rewrite-target: /
spec:
  ingressClassName: nginx
  rules:
    - host: memo.example.com
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: memo-server
                port:
                  number: 80
