apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: memo-prod
resources:
  - ../../base
  - ingress.yaml
commonLabels:
  environment: prod
images:
  - name: ghcr.io/your-org/memo-server
    newName: ghcr.io/your-org/memo-server
    newTag: prod
