apiVersion: v1
kind: ConfigMap
metadata:
  name: memo-app-config
  namespace: memo
  labels:
    app: memo
    tier: api
  annotations:
    memo.f-lab/app: memo-server
    memo.f-lab/env: base
    memo.f-lab/component: config
data:
  APP_NAME: memo-server
