apiVersion: v1
kind: Secret
metadata:
  name: memo-db-secret
  namespace: memo
  labels:
    app: memo
    tier: db
stringData:
  POSTGRES_USER: memo
  POSTGRES_PASSWORD: memo
  POSTGRES_DB: memo
  DATABASE_URL: postgresql://memo:memo@memo-postgres:5432/memo
