apiVersion: v1
kind: Secret
metadata:
  name: memo-db-secret
  namespace: {{ .Values.namespace }}
  labels:
    {{- include "memo-server.labels" . | nindent 4 }}
stringData:
  POSTGRES_USER: {{ .Values.database.user | quote }}
  POSTGRES_PASSWORD: {{ .Values.database.password | quote }}
  POSTGRES_DB: {{ .Values.database.name | quote }}
  DATABASE_URL: {{ include "memo-server.databaseUrl" . | quote }}
