apiVersion: v1
kind: Service
metadata:
  name: memo-postgres
  namespace: {{ .Values.namespace }}
  labels:
    {{- include "memo-server.labels" . | nindent 4 }}
spec:
  selector:
    app: memo-postgres
  ports:
    - port: 5432
      targetPort: 5432
