apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: memo-dev
resources:
  - ../../base
  - ingress.yaml
patchesStrategicMerge:
  - patch-replicas.yaml
commonLabels:
  environment: dev
images:
  - name: ghcr.io/your-org/memo-server
    newName: ghcr.io/your-org/memo-server
    newTag: dev
